version: '3.8'
services:
  server:
    volumes:
      - ./server:/usr/src/app
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    command: yarn run dev
  
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    command: yarn run dev
    volumes:
      - ./client:/usr/src/app