version: '3.8'
services:
  server:
    container_name: safetalk_server
    restart: always
    command: yarn run dev
    build: ./server
    networks:
      - server
      - client
    volumes:
      - ./server:/usr/src/app

  client:
    container_name: safetalk_client
    restart: always
    command: yarn run dev
    depends_on: 
      - server
    build: ./client
    networks:
      - client
    volumes:
      - ./client:/usr/src/app

  nginx:
    container_name: safetalk_nginx
    restart: always
    build: ./nginx
    networks:
      - client
      - server
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - client
      
networks:
  server:
    driver: bridge
  client:
    driver: bridge