const safetalk_test = db.getSiblingDB('safetalk_test')
safetalk_test.createCollection('users')
safetalk_test.createCollection('rooms')
const safetalk = db.getSiblingDB('safetalk_db')
safetalk.createCollection('users')
safetalk.createCollection('rooms')